name       : wordgrinder
version    : 0.7.2
release    : 3
source     :
    - https://github.com/davidgiven/wordgrinder/archive/0.7.2.tar.gz : 4e1bc659403f98479fe8619655f901c8c03eb87743374548b4d20a41d31d1dff
license    : MIT
component  : office
summary    : WordGrinder is a simple, Unicode-aware word processor that runs on the console.
description: |
    WordGrinder is a simple, Unicode-aware word processor that runs on the console. It's designed to get the hell out of your way and let you write; it does very little, but what it does it does well.
builddeps  :
    - pkgconfig(lua-5.3)
    - pkgconfig(minizip)
    - pkgconfig(uthash)
    - pkgconfig(xft)
build      : |
    %make LUA_PACKAGE="--cflags={$(pkg-config --cflags lua-5.3)} --libs={$(pkg-config --libs lua-5.3)}" \
          MINIZIP_PACKAGE="--cflags={$(pkg-config --cflags minizip)} --libs={$(pkg-config --libs minizip)}" \
          UTHASH_PACKAGE="--cflags={$(pkg-config --cflags uthash)} --libs={$(pkg-config --libs uthash)}" \
          DESTDIR=$installdir PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
