name       : wordgrinder
version    : 0.7.1
release    : 1
source     :
    - https://github.com/davidgiven/wordgrinder/archive/0.7.1.tar.gz : 54085af7963e1f67342bc0b1b20d1ccc75494f2e23d401b601cf3089acea747c
license    : MIT
component  : office
summary    : WordGrinder is a simple, Unicode-aware word processor that runs on the console.
description: |
    WordGrinder is a simple, Unicode-aware word processor that runs on the console. It's designed to get the hell out of your way and let you write; it does very little, but what it does it does well.
builddeps  :
    - pkgconfig(lua-5.3)
    - pkgconfig(minizip)
    - pkgconfig(uthash)
    - pkgconfig(xft)
build      : |
    %make LUA_PACKAGE="--cflags={$(pkg-config --cflags lua-5.3)} --libs={$(pkg-config --libs lua-5.3)}" \
          MINIZIP_PACKAGE="--cflags={$(pkg-config --cflags minizip)} --libs={$(pkg-config --libs minizip)}" \
          UTHASH_PACKAGE="--cflags={$(pkg-config --cflags uthash)} --libs={$(pkg-config --libs uthash)}" \
          DESTDIR=$installdir PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
